<?php

declare(strict_types=1);

/**
 * Dữ liệu chung cho báo cáo kiểm thử (HTML, Markdown, Excel).
 * Mỗi test case: [mã, chức năng, các bước, kết quả mong đợi, kết quả, ưu tiên]
 */
return [
    'meta' => [
        'project' => 'Winsum Home',
        'subtitle' => 'Website thương mại điện tử nội thất & chiếu sáng',
        'version' => '1.1',
        'date' => date('d/m/Y'),
        'tester' => 'Nhóm phát triển đồ án',
        'method' => 'Kiểm thử hộp đen, thủ công (Manual Black-box Testing)',
        'environment' => [
            'OS' => 'Windows 10/11',
            'Web server' => 'Apache (XAMPP)',
            'PHP' => '8.0+',
            'Database' => 'MySQL — winsumwebfinal',
            'Browser' => 'Google Chrome, Microsoft Edge',
            'URL' => 'http://localhost/winsumweb/index.php',
        ],
        'conclusion' => 'Winsum Home đáp ứng yêu cầu chức năng của đồ án tốt nghiệp, bao gồm quy trình hoàn hàng 4 giai đoạn (yêu cầu → duyệt → nhận hàng → hoàn tiền). Hệ thống sẵn sàng demo và bảo vệ đồ án.',
        'limitations' => [
            'Chưa có bộ kiểm thử tự động (PHPUnit, Selenium).',
            'Chưa kiểm thử đồng thời nhiều người dùng (race condition tồn kho).',
            'VietQR hiện phục vụ demo; bản vận hành thật cần webhook ngân hàng để đối soát tự động.',
            'Một số bảng DB (carts, wishlists) chưa được sử dụng trong ứng dụng.',
            'Chưa hỗ trợ hoàn hàng từng sản phẩm (partial return); chỉ hoàn toàn bộ đơn.',
            'Chưa kiểm thử upload ảnh bằng chứng với file quá dung lượng / định dạng lạ trên nhiều trình duyệt.',
        ],
        'future' => [
            'Bổ sung PHPUnit cho repository layer (order, return, coupon).',
            'Tích hợp webhook VietQR/Casso/SePay hoặc VNPay/MoMo để xác nhận thanh toán tự động.',
            'Gửi email/SMS thông báo từng giai đoạn hoàn hàng.',
            'Hoàn hàng từng dòng sản phẩm (partial return).',
            'Kiểm thử hiệu năng với JMeter/k6.',
        ],
    ],
    'sections' => [
        ['id' => 'A', 'title' => 'Storefront — Duyệt & tìm kiếm', 'cases' => [
            ['TC-A01', 'Hiển thị trang chủ', '1. Mở http://localhost/winsumweb/index.php hoặc ?view=home', 'Banner, danh mục, sản phẩm bán chạy, tin tức hiển thị đầy đủ', 'Pass', 'Cao'],
            ['TC-A02', 'Điều hướng menu', '1. Click Sản phẩm, Tin tức, Giỏ hàng trên header', 'Chuyển đúng trang tương ứng, URL view= khớp', 'Pass', 'Cao'],
            ['TC-A03', 'Danh mục sản phẩm', '1. Mở ?view=catalog', 'Grid sản phẩm, ảnh, giá, nút thêm giỏ', 'Pass', 'Cao'],
            ['TC-A04', 'Lọc theo danh mục', '1. Chọn category trên catalog', 'Chỉ hiển thị SP thuộc danh mục đã chọn', 'Pass', 'Cao'],
            ['TC-A05', 'Lọc theo khoảng giá', '1. Chọn min/max price trên catalog', 'Danh sách lọc đúng khoảng giá', 'Pass', 'Trung bình'],
            ['TC-A06', 'Phân trang catalog', '1. Chuyển trang 2, 3 trên catalog', 'URL page= đúng, danh sách SP thay đổi', 'Pass', 'Trung bình'],
            ['TC-A07', 'Tìm kiếm site-wide', '1. Gõ từ khóa trên ô search header', 'Gợi ý/kết quả SP liên quan', 'Pass', 'Cao'],
            ['TC-A08', 'Chi tiết sản phẩm', '1. Mở ?view=product&slug=...', 'Ảnh gallery, giá, mô tả, tab đánh giá', 'Pass', 'Cao'],
            ['TC-A09', 'URL slug không tồn tại', '1. Mở ?view=product&slug=khong-ton-tai', 'Thông báo không tìm thấy / redirect hợp lý', 'Pass', 'Trung bình'],
            ['TC-A10', 'View không hợp lệ', '1. Mở ?view=xyz123', 'Fallback về trang chủ (404 logic)', 'Pass', 'Thấp'],
        ]],
        ['id' => 'B', 'title' => 'Giỏ hàng & mã giảm giá', 'cases' => [
            ['TC-B01', 'Thêm SP từ catalog', '1. POST add_to_cart từ catalog', 'Toast thành công, giỏ +1 dòng', 'Pass', 'Cao'],
            ['TC-B02', 'Thêm SP từ trang chi tiết', '1. Chọn SL, bấm thêm giỏ', 'Giỏ cập nhật đúng SL và tổng tiền', 'Pass', 'Cao'],
            ['TC-B03', 'Thêm SP hết hàng', '1. Thêm SP stock_status = out_of_stock', 'Báo lỗi, không thêm vào giỏ', 'Pass', 'Cao'],
            ['TC-B04', 'Cập nhật số lượng', '1. Sửa qty trên trang cart, submit', 'Tổng tiền tính lại đúng', 'Pass', 'Cao'],
            ['TC-B05', 'Xóa dòng giỏ', '1. Bấm xóa item trên cart', 'Dòng biến mất, tổng cập nhật', 'Pass', 'Cao'],
            ['TC-B06', 'Áp mã WINSUMXINCHAO', '1. Nhập mã hợp lệ trên cart', 'Giảm 40.000đ, hiển thị discount', 'Pass', 'Cao'],
            ['TC-B07', 'Mã giảm giá sai', '1. Nhập MASAI trên cart', 'Thông báo mã không hợp lệ', 'Pass', 'Trung bình'],
            ['TC-B08', 'Xóa mã giảm giá', '1. Submit coupon_code rỗng', 'Discount = 0', 'Pass', 'Trung bình'],
            ['TC-B09', 'Admin không thêm giỏ', '1. Đăng nhập admin, thêm SP', 'Báo tài khoản QTV không mua được', 'Pass', 'Cao'],
            ['TC-B10', 'Đồng bộ giá từ DB', '1. Đổi giá SP trên admin, mở lại cart/checkout', 'Giá giỏ đồng bộ khi sync/checkout', 'Pass', 'Trung bình'],
            ['TC-B11', 'Đăng xuất xóa giỏ hàng', '1. Khách thêm SP vào giỏ rồi đăng xuất', 'Session giỏ hàng và coupon bị xóa', 'Pass', 'Cao'],
            ['TC-B12', 'Hoàn lượt coupon khi hủy', '1. Đặt đơn có mã, hủy đơn pending', 'Dùng lại mã thành công (đơn hủy không tính lượt)', 'Pass', 'Cao'],
        ]],
        ['id' => 'C', 'title' => 'Thanh toán (Checkout)', 'cases' => [
            ['TC-C01', 'Giỏ trống vào checkout', '1. Mở checkout khi giỏ rỗng', 'Không cho đặt / báo giỏ trống', 'Pass', 'Cao'],
            ['TC-C02', 'Form checkout guest', '1. Điền họ tên, SĐT, email, tỉnh/thành phố, phường/xã, địa chỉ cụ thể', 'Validate đủ trường bắt buộc', 'Pass', 'Cao'],
            ['TC-C03', 'Thiếu thông tin bắt buộc', '1. Bỏ trống SĐT hoặc địa chỉ, submit', 'Báo "Vui lòng điền đầy đủ"', 'Pass', 'Cao'],
            ['TC-C04', 'Chọn vận chuyển', '1. Chọn phương thức shipping', 'Phí ship cộng vào tổng', 'Pass', 'Cao'],
            ['TC-C05', 'Chọn thanh toán', '1. Chọn COD hoặc Chuyển khoản VietQR', 'Lưu payment_method_id và hiển thị đúng phương thức', 'Pass', 'Cao'],
            ['TC-C06', 'Đặt hàng thành công', '1. Submit checkout_submit hợp lệ', 'Mã đơn WS..., giỏ xóa, thông báo thành công', 'Pass', 'Cao'],
            ['TC-C07', 'Checkout có mã giảm giá', '1. Áp coupon trước khi đặt', 'discount_amount ghi vào đơn', 'Pass', 'Cao'],
            ['TC-C08', 'Checkout đã đăng nhập', '1. Customer login rồi đặt', 'orders.customer_id gắn đúng', 'Pass', 'Cao'],
            ['TC-C09', 'Trừ tồn kho', '1. Đặt SP còn hàng', 'stock giảm / alert nếu hết', 'Pass', 'Cao'],
            ['TC-C10', 'Admin không checkout', '1. Admin session thử đặt', 'Từ chối đặt hàng', 'Pass', 'Trung bình'],
            ['TC-C11', 'Ràng buộc SĐT', '1. Nhập SĐT không đủ 10 số hoặc không bắt đầu bằng 0', 'Không cho đặt hàng, hiển thị lỗi rõ ràng', 'Pass', 'Cao'],
            ['TC-C12', 'VietQR demo', '1. Chọn VietQR, đặt hàng, bấm Tôi đã thanh toán', 'payment_status = paid, chuyển trang đơn/tra cứu', 'Pass', 'Cao'],
            ['TC-C13', 'VietQR đơn đã hủy', '1. Xác nhận VietQR cho đơn cancelled/returned', 'Hệ thống từ chối xác nhận thanh toán', 'Pass', 'Cao'],
            ['TC-C14', 'Validate coupon theo SĐT checkout', '1. Guest áp mã, nhập SĐT đã hết lượt ở checkout', 'Không cho đặt hoặc xóa coupon và báo lỗi', 'Pass', 'Cao'],
        ]],
        ['id' => 'D', 'title' => 'Xác thực khách hàng', 'cases' => [
            ['TC-D01', 'Đăng ký tài khoản', '1. Popup đăng ký, điền form hợp lệ', 'Tạo customer, login session', 'Pass', 'Cao'],
            ['TC-D02', 'Đăng ký trùng SĐT/email', '1. Dùng SĐT đã có', 'Báo lỗi trùng', 'Pass', 'Cao'],
            ['TC-D03', 'Đăng nhập đúng', '1. Email/SĐT + mật khẩu đúng', 'Session customer, redirect OK', 'Pass', 'Cao'],
            ['TC-D04', 'Đăng nhập sai', '1. Mật khẩu sai', 'Báo lỗi, không login', 'Pass', 'Cao'],
            ['TC-D05', 'Đăng xuất', '1. Logout từ account', 'Session xóa, về home', 'Pass', 'Trung bình'],
            ['TC-D06', 'Cập nhật hồ sơ', '1. Sửa tên, SĐT, email', 'DB cập nhật', 'Pass', 'Trung bình'],
            ['TC-D07', 'Đổi mật khẩu', '1. Nhập new_password hợp lệ', 'Hash mới lưu DB', 'Pass', 'Trung bình'],
            ['TC-D08', 'Guest đăng ký cùng SĐT đơn cũ', '1. Đặt guest rồi đăng ký cùng phone', 'Đơn cũ gắn customer_id', 'Pass', 'Trung bình'],
            ['TC-D09', 'Đăng xuất xóa giỏ', '1. Đăng nhập khách, thêm hàng, đăng xuất', 'Giỏ hàng cũ không còn sau logout', 'Pass', 'Cao'],
            ['TC-D10', 'Khóa khách & rate limit login', '1. Admin khóa khách đang login; nhập sai MK 5 lần', 'Session khách bị xóa; đăng nhập chặn 15 phút', 'Pass', 'Cao'],
        ]],
        ['id' => 'E', 'title' => 'Đơn hàng khách hàng', 'cases' => [
            ['TC-E01', 'Danh sách đơn', '1. Login khách, mở ?view=orders', 'Liệt kê đơn của user, phân trang nếu có', 'Pass', 'Cao'],
            ['TC-E02', 'Chi tiết đơn', '1. Click mã đơn trên danh sách', 'Items, tổng tiền, trạng thái, thanh toán', 'Pass', 'Cao'],
            ['TC-E03', 'Hủy đơn pending', '1. Cancel trên order-detail đơn pending', 'status = cancelled, hoàn kho', 'Pass', 'Cao'],
            ['TC-E04', 'Không hủy đơn đã giao', '1. Thử hủy delivered', 'Từ chối / báo lỗi', 'Pass', 'Trung bình'],
            ['TC-E05', 'Guest không xem orders', '1. Chưa login mở ?view=orders', 'Yêu cầu đăng nhập', 'Pass', 'Trung bình'],
            ['TC-E06', 'Chỉ xem đơn của mình', '1. User A mở đơn user B (URL code)', 'Từ chối truy cập', 'Pass', 'Cao'],
            ['TC-E07', 'Tra cứu đơn guest', '1. Nhập mã đơn + SĐT tại ?view=order-lookup', 'Hiển thị chi tiết đơn không cần đăng nhập', 'Pass', 'Cao'],
            ['TC-E08', 'Guest hủy đơn pending', '1. Tra cứu đơn guest rồi bấm hủy', 'Đơn pending → cancelled và hoàn kho', 'Pass', 'Cao'],
            ['TC-E09', 'Không hủy đơn đang giao', '1. Đơn fulfillment_status = shipped, khách bấm hủy', 'Hệ thống từ chối hủy đơn', 'Pass', 'Cao'],
            ['TC-E10', 'Đồng bộ trạng thái đơn/vận chuyển', '1. Admin đổi giao hàng shipped/delivered/cancelled', 'status và fulfillment_status đồng bộ', 'Pass', 'Cao'],
            ['TC-E11', 'CTA hoàn hàng trên chi tiết đơn', '1. Login, mở đơn delivered trong 7 ngày. 2. Kiểm tra nút/link hoàn hàng', 'Hiển thị link «Yêu cầu hoàn hàng / Trả tiền» dẫn tới ?view=order-return&code=...', 'Pass', 'Cao'],
            ['TC-E12', 'Hết hạn hoàn hàng', '1. Mở đơn delivered_at > 7 ngày', 'Không hiển thị CTA hoàn hàng; order-return báo hết hạn', 'Pass', 'Cao'],
            ['TC-E13', 'Trang hoàn hàng riêng', '1. Từ order-detail bấm CTA hoàn hàng', 'Mở trang ?view=order-return&code=..., breadcrumb và tiêu đề đúng', 'Pass', 'Cao'],
            ['TC-E14', 'Gửi yêu cầu hoàn đầy đủ', '1. Điền lý do, STK ngân hàng, tên TK, ngân hàng, upload ảnh. 2. Submit', 'Tạo order_return_requests status=pending; đơn → return_pending; chưa hoàn tiền', 'Pass', 'Cao'],
            ['TC-E15', 'Thiếu ảnh bằng chứng', '1. Submit form hoàn không chọn file ảnh', 'Báo lỗi bắt buộc ảnh; không tạo request', 'Pass', 'Cao'],
            ['TC-E16', 'Thiếu thông tin ngân hàng', '1. Bỏ trống STK hoặc tên TK hoặc tên ngân hàng', 'Báo lỗi validate; không tạo request', 'Pass', 'Cao'],
            ['TC-E17', 'Không gửi yêu cầu trùng', '1. Đơn đang return_pending/accepted/received, thử mở form hoàn lại', 'Ẩn form / báo đang xử lý; không tạo request thứ hai', 'Pass', 'Cao'],
            ['TC-E18', 'Không hủy đơn khi đang hoàn', '1. Đơn return_pending, khách bấm hủy', 'Từ chối hủy; giữ nguyên luồng hoàn', 'Pass', 'Cao'],
            ['TC-E19', 'Tiến độ hoàn trên order-detail', '1. Sau mỗi giai đoạn (pending→accepted→received→returned) mở order-detail', 'Hiển thị đúng nhãn: chờ duyệt / chờ trả hàng / đã nhận hàng chờ hoàn tiền / hoàn thành', 'Pass', 'Cao'],
            ['TC-E20', 'Hướng dẫn trả hàng sau duyệt', '1. Admin accept yêu cầu hoàn. 2. Khách xem order-detail', 'Hiển thị địa chỉ kho nhận hàng hoàn và hướng dẫn gửi lại', 'Pass', 'Cao'],
            ['TC-E21', 'Đơn bị từ chối hoàn', '1. Admin reject yêu cầu hoàn. 2. Khách xem order-detail', 'Đơn về delivered; có thể gửi yêu cầu mới nếu còn hạn', 'Pass', 'Cao'],
            ['TC-E22', 'Guest không gửi hoàn hàng', '1. Chưa login mở ?view=order-return&code=...', 'Yêu cầu đăng nhập, không hiện form', 'Pass', 'Cao'],
        ]],
        ['id' => 'F', 'title' => 'Đánh giá sản phẩm', 'cases' => [
            ['TC-F01', 'Gửi review', '1. Form submit_review trên product', 'Tạo review status approved, hiển thị ngay', 'Pass', 'Trung bình'],
            ['TC-F02', 'Review thiếu nội dung', '1. Bỏ trống content', 'Validate báo lỗi', 'Pass', 'Trung bình'],
            ['TC-F03', 'Rating cập nhật ngay', '1. Gửi review hợp lệ', 'rating_average và rating_count SP cập nhật', 'Pass', 'Trung bình'],
            ['TC-F04', 'Review từ chối (legacy)', '1. Admin reject review pending cũ', 'Không hiện công khai', 'Pass', 'Thấp'],
            ['TC-F05', 'Chỉ đánh giá đơn đã giao', '1. Khách mở SP thuộc đơn chưa delivered', 'Không hiển thị form / backend từ chối', 'Pass', 'Cao'],
            ['TC-F06', 'Chặn đánh giá trùng', '1. Khách đã đánh giá SP, gửi lần 2', 'Báo đã đánh giá sản phẩm này rồi', 'Pass', 'Cao'],
            ['TC-F07', 'Ẩn form sau đánh giá', '1. Khách đã gửi review thành công', 'Form ẩn, thông báo đã đánh giá', 'Pass', 'Cao'],
        ]],
        ['id' => 'G', 'title' => 'Blog & bình luận', 'cases' => [
            ['TC-G01', 'Danh sách blog', '1. Mở ?view=blog', 'Grid bài viết, excerpt 4 dòng', 'Pass', 'Trung bình'],
            ['TC-G02', 'Phân trang blog', '1. Chuyển trang 2', '6 bài/trang, pagination catalog style', 'Pass', 'Trung bình'],
            ['TC-G03', 'Chi tiết bài viết', '1. Click bài ?view=post&slug=...', 'Nội dung, không ảnh cover đầu trang', 'Pass', 'Trung bình'],
            ['TC-G04', 'Sidebar blog', '1. Xem sidebar blog', 'Danh mục, bài nổi bật', 'Pass', 'Thấp'],
            ['TC-G05', 'Gửi bình luận', '1. submit_comment trên post', 'Tạo comment pending', 'Pass', 'Trung bình'],
            ['TC-G06', 'Comment sau duyệt', '1. Admin approve comment', 'Hiện dưới bài viết', 'Pass', 'Trung bình'],
            ['TC-G07', 'Blog editor (admin)', '1. Tạo/sửa bài ?view=blog-editor', 'Lưu draft/published', 'Pass', 'Trung bình'],
            ['TC-G08', 'UTF-8 tiếng Việt blog', '1. Xem tiêu đề/nội dung VN', 'Không lỗi ????', 'Pass', 'Cao'],
        ]],
        ['id' => 'H', 'title' => 'Admin — Đăng nhập & Dashboard', 'cases' => [
            ['TC-H01', 'Đăng nhập admin', '1. Login admin@winsumhome.vn / mật khẩu admin', 'Vào admin-dashboard', 'Pass', 'Cao'],
            ['TC-H02', 'Chặn guest admin', '1. Truy cập admin-products không login', 'Redirect / từ chối', 'Pass', 'Cao'],
            ['TC-H03', 'Dashboard thống kê', '1. Xem admin-dashboard', 'Số đơn, doanh thu thuần, cảnh báo tồn kho', 'Pass', 'Trung bình'],
            ['TC-H04', 'Đăng xuất admin', '1. admin_logout', 'Về storefront', 'Pass', 'Trung bình'],
            ['TC-H05', 'COD auto paid khi giao', '1. Admin chuyển đơn COD sang delivered', 'payment_status = paid tự động', 'Pass', 'Cao'],
            ['TC-H06', 'Doanh thu chưa trừ khi chờ hoàn', '1. Có đơn return_pending/accepted/received. 2. Xem dashboard revenue_net', 'revenue_net không giảm cho đến khi đơn returned', 'Pass', 'Cao'],
            ['TC-H07', 'Doanh thu hoàn sau giai đoạn 4', '1. Admin complete refund. 2. Refresh dashboard', 'revenue_refunded tăng; revenue_net giảm tương ứng', 'Pass', 'Cao'],
            ['TC-H08', 'Cảnh báo đơn chờ hoàn', '1. Có yêu cầu hoàn pending trên admin-returns', 'Dashboard hoặc menu admin phản ánh số đơn cần xử lý (nếu có)', 'Pass', 'Trung bình'],
        ]],
        ['id' => 'I', 'title' => 'Admin — Sản phẩm & tồn kho', 'cases' => [
            ['TC-I01', 'Danh sách SP admin', '1. Mở admin-products', 'Bảng SP, phân trang', 'Pass', 'Cao'],
            ['TC-I02', 'Tìm kiếm SP admin', '1. Tìm theo tên/SKU/slug', 'Lọc đúng kết quả', 'Pass', 'Trung bình'],
            ['TC-I03', 'Thêm sản phẩm', '1. save_product form mới', 'SP hiện trên catalog', 'Pass', 'Cao'],
            ['TC-I04', 'Sửa sản phẩm', '1. save_product với id', 'Thay đổi phản ánh web', 'Pass', 'Cao'],
            ['TC-I05', 'Ẩn/xóa sản phẩm', '1. delete_product', 'SP ẩn khỏi storefront', 'Pass', 'Trung bình'],
            ['TC-I06', 'Cảnh báo hết hàng', '1. Đặt hết SP cuối cùng', 'Alert trên dashboard/products', 'Pass', 'Cao'],
            ['TC-I07', 'Đánh dấu đã xử lý alert', '1. mark_inventory_read', 'Alert biến mất/không đếm', 'Pass', 'Trung bình'],
            ['TC-I08', 'Upload ảnh SP', '1. Thêm URL/upload ảnh', 'Hiển thị trên chi tiết SP', 'Pass', 'Trung bình'],
            ['TC-I09', 'Tách trang thêm/sửa sản phẩm', '1. admin-products → thêm/sửa chi tiết', 'Mở admin-product-create / admin-product-edit', 'Pass', 'Cao'],
            ['TC-I10', 'Lưu SP và tồn kho cùng transaction', '1. Sửa thông tin + số lượng tồn kho', 'Rollback nếu lỗi; cả hai cùng lưu khi thành công', 'Pass', 'Cao'],
        ]],
        ['id' => 'J', 'title' => 'Admin — Đơn hàng', 'cases' => [
            ['TC-J01', 'Danh sách đơn', '1. Mở admin-orders', 'Lọc, tìm mã đơn/SĐT, xem trạng thái thanh toán', 'Pass', 'Cao'],
            ['TC-J02', 'Chi tiết đơn admin', '1. admin-order-detail?code=...', 'Items, khách, lịch sử trạng thái', 'Pass', 'Cao'],
            ['TC-J03', 'Cập nhật thanh toán', '1. update_payment_status → paid', 'Dashboard doanh thu cập nhật (đơn chưa returned)', 'Pass', 'Cao'],
            ['TC-J04', 'Cập nhật giao hàng', '1. update_fulfillment_status', 'Trạng thái fulfillment đổi', 'Pass', 'Cao'],
            ['TC-J05', 'Lịch sử trạng thái', '1. Đổi trạng thái nhiều lần', 'order_status_history ghi log đầy đủ', 'Pass', 'Trung bình'],
            ['TC-J06', 'CSRF trên form đơn', '1. POST không token', 'Từ chối cập nhật', 'Pass', 'Trung bình'],
            ['TC-J07', 'Khóa trạng thái cuối & luồng hoàn', '1. Đơn cancelled/returned/delivered hoặc return_pending/accepted/received, admin đổi shipped', 'Hệ thống từ chối cập nhật trái luồng', 'Pass', 'Cao'],
            ['TC-J08', 'Xem đơn theo khách', '1. Từ chi tiết khách bấm xem đơn hàng', 'Chỉ hiện đơn của khách đó', 'Pass', 'Cao'],
            ['TC-J09', 'Hoàn kho khi hủy', '1. Khách hủy đơn đã trừ kho', 'inventory_items tăng lại, inventory_restocked = 1', 'Pass', 'Cao'],
            ['TC-J10', 'Khóa lùi shipped', '1. Đơn shipped, admin đổi giao hàng về pending', 'Hệ thống từ chối', 'Pass', 'Cao'],
            ['TC-J11', 'Khóa thanh toán đơn cuối', '1. Đơn delivered/cancelled/returned, admin đổi payment', 'Form disabled và backend từ chối', 'Pass', 'Cao'],
            ['TC-J12', 'Admin không set returned trực tiếp', '1. Admin chọn returned trên admin-orders', 'Không có option / backend từ chối', 'Pass', 'Cao'],
            ['TC-J13', 'Không đổi payment khi đang hoàn', '1. Đơn return_pending, admin thử đổi payment_status', 'Form khóa / backend từ chối', 'Pass', 'Cao'],
            ['TC-J14', 'Lịch sử giai đoạn hoàn', '1. Chạy đủ 4 giai đoạn hoàn. 2. Xem order_status_history', 'Ghi customer_return, return_accept, return_goods_received, return_complete', 'Pass', 'Cao'],
            ['TC-J15', 'Hoàn coupon khi returned', '1. Đơn có coupon, hoàn thành giai đoạn 4', 'Lượt dùng coupon được giải phóng (có thể dùng lại)', 'Pass', 'Cao'],
        ]],
        ['id' => 'K', 'title' => 'Admin — Khách hàng, đánh giá, blog, hoàn hàng', 'cases' => [
            ['TC-K01', 'Danh sách khách', '1. Mở admin-customers', 'Phân trang, lọc', 'Pass', 'Trung bình'],
            ['TC-K02', 'Khóa/mở khách', '1. toggle_customer_block', 'status cập nhật', 'Pass', 'Trung bình'],
            ['TC-K03', 'Xóa review', '1. admin-reviews delete', 'Review biến mất, rating SP tính lại', 'Pass', 'Trung bình'],
            ['TC-K04', 'Duyệt review legacy', '1. admin-reviews approve (pending cũ)', 'Review cũ chuyển approved', 'Pass', 'Thấp'],
            ['TC-K05', 'Quản lý blog', '1. set_blog_status, delete', 'Storefront phản ánh', 'Pass', 'Trung bình'],
            ['TC-K06', 'Duyệt bình luận blog', '1. admin-blog-comments approve', 'Comment hiện trên post', 'Pass', 'Trung bình'],
            ['TC-K07', 'Trang admin-returns & tabs', '1. Mở ?view=admin-returns', 'Hiển thị tabs: Chờ duyệt / Đã duyệt chờ hàng / Đã nhận hàng / Hoàn tất / Từ chối', 'Pass', 'Cao'],
            ['TC-K08', 'Giai đoạn 2 — Duyệt yêu cầu (accept)', '1. Tab Chờ duyệt, bấm Duyệt + ghi chú. 2. POST return_accept', 'Request → accepted; đơn → return_accepted; chưa hoàn tiền, chưa cộng kho', 'Pass', 'Cao'],
            ['TC-K09', 'Giai đoạn 2 — Từ chối (reject)', '1. Tab Chờ duyệt, bấm Từ chối + lý do', 'Request → rejected; đơn → delivered', 'Pass', 'Cao'],
            ['TC-K10', 'Giai đoạn 3 — Xác nhận nhận hàng', '1. Tab Đã duyệt, bấm Đã nhận hàng hoàn, nhập phí ship hoàn (nếu có)', 'Request → goods_received; đơn → return_received; tồn kho SP được cộng lại', 'Pass', 'Cao'],
            ['TC-K11', 'Giai đoạn 4 — Hoàn tiền', '1. Tab Đã nhận hàng, bấm Hoàn tiền', 'Request → completed; đơn → returned; payment_status → refunded', 'Pass', 'Cao'],
            ['TC-K12', 'Xem ảnh & STK ngân hàng', '1. Mở chi tiết yêu cầu hoàn trên admin-returns', 'Hiển thị ảnh bằng chứng, STK, tên TK, ngân hàng khách cung cấp', 'Pass', 'Cao'],
            ['TC-K13', 'CSRF trên action hoàn', '1. POST return_accept/confirm_goods/complete_refund không token', 'Từ chối thao tác', 'Pass', 'Trung bình'],
            ['TC-K14', 'Không skip giai đoạn', '1. Thử complete_refund khi request còn pending', 'Backend từ chối; bắt buộc đúng thứ tự 4 bước', 'Pass', 'Cao'],
        ]],
        ['id' => 'L', 'title' => 'Bảo mật & dữ liệu', 'cases' => [
            ['TC-L01', 'CSRF form POST', '1. Gửi POST thiếu csrf_token', 'Từ chối / báo phiên không hợp lệ', 'Pass', 'Cao'],
            ['TC-L02', 'Prepared statements', '1. Nhập SQL injection trong search', 'Không lỗi DB, không lộ data', 'Pass', 'Cao'],
            ['TC-L03', 'XSS output', '1. Nhập <script> trong review', 'Escape HTML khi hiển thị', 'Pass', 'Cao'],
            ['TC-L04', 'Phân quyền admin', '1. Customer thường vào admin URL', 'Bị chặn', 'Pass', 'Cao'],
            ['TC-L05', 'Session cart isolation', '1. Hai trình duyệt khác nhau', 'Giỏ độc lập theo session', 'Pass', 'Trung bình'],
            ['TC-L06', 'Encoding UTF-8', '1. Dữ liệu tiếng Việt toàn site', 'Không ???? trên UI', 'Pass', 'Cao'],
            ['TC-L07', 'SĐT hợp lệ', '1. Form checkout/register/profile với SĐT sai', 'Backend từ chối nếu không đúng 10 số bắt đầu 0', 'Pass', 'Cao'],
        ]],
        ['id' => 'M', 'title' => 'Giao diện & tương thích', 'cases' => [
            ['TC-M01', 'Responsive header', '1. Thu nhỏ viewport 768px', 'Menu/mobile usable', 'Pass', 'Trung bình'],
            ['TC-M02', 'Flash message', '1. Thao tác thành công/thất bại', 'Toast/notice hiển thị', 'Pass', 'Trung bình'],
            ['TC-M03', 'Pagination style', '1. Blog & catalog pagination', 'Class catalog-pagination thống nhất', 'Pass', 'Thấp'],
            ['TC-M04', '404 / fallback view', '1. view=unknown', 'Về home an toàn', 'Pass', 'Thấp'],
            ['TC-M05', 'Nút quay lại dùng chung', '1. Mở trang bất kỳ khác home', 'Có nút quay lại trang trước ở đầu nội dung', 'Pass', 'Trung bình'],
            ['TC-M06', 'UI form hoàn hàng', '1. Mở ?view=order-return', 'Form dùng checkout-form, label/input giãn cách hợp lý', 'Pass', 'Trung bình'],
            ['TC-M07', 'Bo góc input hoàn hàng', '1. Kiểm tra select, textarea, file upload trên order-return', 'border-radius đồng bộ, không góc vuông lệch theme', 'Pass', 'Trung bình'],
            ['TC-M08', 'Breadcrumb trang hoàn', '1. Xem breadcrumb order-return', 'Trang chủ / Đơn hàng / Chi tiết đơn / Hoàn hàng', 'Pass', 'Thấp'],
            ['TC-M09', 'Tiến độ hoàn trực quan', '1. Xem order-detail khi đang hoàn', 'Thanh/bước tiến độ 4 giai đoạn hiển thị rõ', 'Pass', 'Trung bình'],
        ]],
        ['id' => 'N', 'title' => 'Hoàn hàng 4 giai đoạn — Luồng E2E', 'cases' => [
            ['TC-N01', 'E2E — Giai đoạn 1 khách gửi yêu cầu', '1. Đặt đơn COD/VietQR, admin giao delivered. 2. Khách gửi form hoàn đầy đủ trong 7 ngày', 'order_return_requests.status=pending; orders.status=return_pending; payment chưa refunded', 'Pass', 'Cao'],
            ['TC-N02', 'E2E — Giai đoạn 2 admin duyệt', '1. Admin accept yêu cầu TC-N01', 'request=accepted; order=return_accepted; khách thấy hướng dẫn trả hàng', 'Pass', 'Cao'],
            ['TC-N03', 'E2E — Giai đoạn 3 nhận hàng hoàn', '1. Admin confirm goods received', 'request=goods_received; order=return_received; inventory tăng lại', 'Pass', 'Cao'],
            ['TC-N04', 'E2E — Giai đoạn 4 hoàn tiền', '1. Admin complete refund', 'request=completed; order=returned; payment_status=refunded', 'Pass', 'Cao'],
            ['TC-N05', 'E2E — Từ chối và gửi lại', '1. Gửi yêu cầu hoàn. 2. Admin reject. 3. Khách gửi lại (còn hạn)', 'Lần 1 rejected→delivered; lần 2 tạo request pending mới', 'Pass', 'Cao'],
            ['TC-N06', 'Đơn VietQR đã paid khi hoàn', '1. Đơn VietQR paid + delivered. 2. Chạy đủ 4 giai đoạn', 'Cuối cùng refunded; không double-count doanh thu', 'Pass', 'Cao'],
            ['TC-N07', 'Đơn COD auto paid khi hoàn', '1. Đơn COD delivered (auto paid). 2. Chạy đủ 4 giai đoạn', 'refunded sau giai đoạn 4; revenue_net điều chỉnh', 'Pass', 'Cao'],
            ['TC-N08', 'Phí ship hoàn ghi nhận', '1. Admin nhập return_shipping_cost ở giai đoạn 3', 'Giá trị lưu vào order_return_requests', 'Pass', 'Trung bình'],
            ['TC-N09', 'Timestamp từng giai đoạn', '1. Sau mỗi bước admin, kiểm tra DB', 'accepted_at, goods_received_at, completed_at (hoặc tương đương) được ghi', 'Pass', 'Trung bình'],
            ['TC-N10', 'Upload ảnh lưu đường dẫn', '1. Khách upload ảnh JPG/PNG hợp lệ', 'File lưu uploads/returns/...; admin xem được', 'Pass', 'Cao'],
            ['TC-N11', 'Không hoàn kho ở giai đoạn 1–2', '1. Sau pending và accepted, kiểm tra inventory', 'Tồn kho chưa tăng; chỉ tăng ở goods_received', 'Pass', 'Cao'],
            ['TC-N12', 'Không refunded ở giai đoạn 1–3', '1. Sau pending, accepted, goods_received', 'payment_status vẫn paid (hoặc trạng thái trước hoàn); chưa refunded', 'Pass', 'Cao'],
            ['TC-N13', 'Đơn không đủ điều kiện hoàn', '1. Đơn pending/shipped/cancelled, thử mở order-return', 'Báo không đủ điều kiện; không hiện form', 'Pass', 'Cao'],
            ['TC-N14', 'Chỉ chủ đơn gửi hoàn', '1. Customer B thử order-return với code đơn của A', 'Từ chối / không tìm thấy đơn', 'Pass', 'Cao'],
            ['TC-N15', 'Lưu lý do hoàn & ghi chú admin', '1. Khách nhập reason; admin nhập note khi accept/reject/refund', 'Nội dung lưu DB và hiển thị trên admin-returns', 'Pass', 'Trung bình'],
        ]],
    ],
];
